language: nix

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4

before_install:
  - sudo mkdir -p /etc/nix

before_script:
  - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf

script:
  - HOME=/homeless-shelter NIX_PATH=nixpkgs=$(pwd) nix-build ./default.nix --no-out-link --keep-going -A xonsh --option restrict-eval true --option build-timeout 1800 --argstr system x86_64-darwin --show-trace
